version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: odonto
      MYSQL_USER: developer
      MYSQL_PASSWORD: 124217
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docs/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3307:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: laravel
    depends_on:
      - mysql
    volumes:
      - ./back:/var/www/html
    ports:
      - "8082:80"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: react
    volumes: []
    ports:
      - "4173:4173"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
